The Brand/Controllers/ShoppingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using The_Brand.Models;
using The_Brand.ViewModel;

namespace The_Brand.Controllers
{
    public class ShoppingController : Controller
    {
        private TheBrandDBEntities objECartDbEntities;
        List<ShoppingCartModel> listOfShoppingCartModels;
        public ShoppingController()
        {
            objECartDbEntities = new TheBrandDBEntities();
            listOfShoppingCartModels = new List<ShoppingCartModel>();
        }
        // GET: Shopping
        public ActionResult Index()
        {
            IEnumerable<ShoppingViewModel> listOfShoppingViewModels = (from objItem in objECartDbEntities.Items
                                                                       join
                                                                       objCate in objECartDbEntities.Categories
                                                                       on objItem.CategoryId equals objCate.CategoryId
                                                                       select new ShoppingViewModel()
                                                                       {
                                                                           ImagePath = objItem.ImagePath,
                                                                           ItemName = objItem.ItemName,
                                                                           Description = objItem.Description,
                                                                           ItemPrice = objItem.ItemPrice,
                                                                           ItemId = objItem.ItemId,
                                                                           Category = objCate.CategoryName,
                                                                           ItemCode = objItem.ItemCode
                                                                       }
                                                                       ).ToList();
            return View(listOfShoppingViewModels);
        }
        public ActionResult search(string Search)
        {
            IEnumerable<ShoppingViewModel> listOfShoppingViewModels = (from objItem in objECartDbEntities.Items
                                                                       join
                                                                       objCate in objECartDbEntities.Categories
                                                                       on objItem.CategoryId equals objCate.CategoryId
                                                                       select new ShoppingViewModel()
                                                                       {
                                                                           ImagePath = objItem.ImagePath,
                                                                           ItemName = objItem.ItemName,
                                                                           Description = objItem.Description,
                                                                           ItemPrice = objItem.ItemPrice,
                                                                           ItemId = objItem.ItemId,
                                                                           Category = objCate.CategoryName,
                                                                           ItemCode = objItem.ItemCode
                                                                       }
                                                                       ).ToList();
            if (Search != null)
            {
                if (listOfShoppingViewModels.Where(x => x.ItemName.StartsWith(Search) || x.ItemName.ToUpper()==(Search.ToUpper())).ToList().Count() != 0)
                    return View(listOfShoppingViewModels.Where(x => x.ItemName.StartsWith(Search)).ToList());
                else return View(listOfShoppingViewModels);
            }
            else return View(listOfShoppingViewModels);
        }
        public ActionResult category(string cat)
        {
            IEnumerable<ShoppingViewModel> listOfShoppingViewModels = (from objItem in objECartDbEntities.Items
                                                                       join
                                                                       objCate in objECartDbEntities.Categories
                                                                       on objItem.CategoryId equals objCate.CategoryId
                                                                       select new ShoppingViewModel()
                                                                       {
                                                                           ImagePath = objItem.ImagePath,
                                                                           ItemName = objItem.ItemName,
                                                                           Description = objItem.Description,
                                                                           ItemPrice = objItem.ItemPrice,
                                                                           ItemId = objItem.ItemId,
                                                                           Category = objCate.CategoryName,
                                                                           ItemCode = objItem.ItemCode
                                                                       }
                                                                      ).ToList();
                return View(listOfShoppingViewModels.Where(x => x.Category == cat.ToUpper()).ToList());
        }
        [HttpPost]
        public JsonResult Index(string ItemId)
        {
            ShoppingCartModel objShoppingCartModel = new ShoppingCartModel();
            Items objItem = objECartDbEntities.Items.Single(model => model.ItemId.ToString() == ItemId);
            if (Session["CartCounter"] != null)
            {
                listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
            }
            if (listOfShoppingCartModels.Any(model => model.ItemId == ItemId))
            {
                objShoppingCartModel = listOfShoppingCartModels.Single(model => model.ItemId == ItemId);
                objShoppingCartModel.Quantity = objShoppingCartModel.Quantity + 1;
                objShoppingCartModel.Total = objShoppingCartModel.Quantity * objShoppingCartModel.UnitPrice;
            }
            else
            {
                objShoppingCartModel.ItemId = ItemId;
                objShoppingCartModel.ImagePath = objItem.ImagePath;
                objShoppingCartModel.ItemName = objItem.ItemName;
                objShoppingCartModel.Quantity = 1;
                objShoppingCartModel.Total = objItem.ItemPrice;
                objShoppingCartModel.UnitPrice = objItem.ItemPrice;
                listOfShoppingCartModels.Add(objShoppingCartModel);
            }
            Session["CartCounter"] = listOfShoppingCartModels.Count;
            Session["CartItem"] = listOfShoppingCartModels;

            return Json(new { Success = true, Counter = listOfShoppingCartModels.Count }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ShoppingCart()
        {
            listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
            return View(listOfShoppingCartModels);
        }
        [HttpPost]
        public ActionResult AddOrder()
        {
            int OrderId = 0;
            listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
            Orders orderObj = new Orders()
            {
                OrderDate = DateTime.Now,
                OrderNumber = string.Format("{0:ddmmyyyyHHmmsss}", DateTime.Now)
            };
            objECartDbEntities.Orders.Add(orderObj);
            objECartDbEntities.SaveChanges();
            OrderId = orderObj.OrderId;
            foreach (var item in listOfShoppingCartModels)
            {
                OrderDetails objOrderDetail = new OrderDetails();
                objOrderDetail.Total = item.Total;
                objOrderDetail.ItemId = item.ItemId;
                objOrderDetail.OrderId = OrderId;
                objOrderDetail.Quantity = item.Quantity;
                objOrderDetail.UnitPrice = item.UnitPrice;

                objECartDbEntities.OrderDetails.Add(objOrderDetail);
                objECartDbEntities.SaveChanges();
            }
            Session["CartItem"] = null;
            Session["CartCounter"] = null;
            return RedirectToAction("index");
        }

        public ActionResult RemovefromCart(Guid ItemId)
        {
            List<ShoppingCartModel> cart = Session["CartItem"] as List<ShoppingCartModel>;
            if (cart.Count() > 1)
            {
                foreach (var item in cart)
                    if (item.ItemId.ToString() == ItemId.ToString())
                    {
                        cart.Remove(item);
                        Session["CartItem"] = cart;
                        Session["CartCounter"] = cart.Count;
                        break;
                    }
                return Redirect("ShoppingCart");
            }
            else
            {
                foreach (var item in cart)
                    if (item.ItemId.ToString() == ItemId.ToString())
                    {
                        cart.Remove(item);
                        Session["CartItem"] = null;
                        Session["CartCounter"] = null;
                        break;
                    }
                return Redirect("index");
            }
        }
    }
}

The Brand/Views/Shared/_Admin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>The Brand</title>
    <link href="~/css/Admin.css" rel="stylesheet" />
    <link href="~/css/add.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
    <script src="~/js/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
</head>
<body style="padding: 0;margin: 0;">
    <div class="wrapper">
        <header>
            <img src="~/img/Logo.png" alt="The brand Logo" />
            <span class="Logo">ADMIN</span>

            @Html.Partial("_AdminSignin")
            <nav >
                <div class="User">
                    <span class="Store">@Html.ActionLink("Go to Store", "Index" ,"Shopping")</span>
                </div>
            </nav>
        </header>

        <section style=" margin: 55px 0px;">
            @RenderBody()
        </section>

        <footer>
            <img src="~/img/Logo.png" alt="The brand Logo" />
            <p>
                Copyright © 2020, All Rights Reserved.
            </p>
            <span class="realized">
                realized by :
                <a class="name"> Hamza Boulila</a>
            </span>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</body>
</html>

The Brand/Views/Shared/_AdminSignin.cshtml
    <nav>
        <div class="User">
            <span><a href="@Url.Action("LogOut", "Login")">LogOut</a></span>
        </div>
    </nav>
    <nav>
        <div class="User">
            <span>Hi, @Session["userName"].ToString()</span>
        </div>
    </nav>

The Brand/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Brand</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/stylecart.css" rel="stylesheet" />
    <link href="~/css/add.css" rel="stylesheet" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
    <script src="~/js/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
</head>
<body>
    <div class="wrapper">
        <header>
            <a href="/Shopping"><img src="~/img/Logo.png" /></a>
            <div class="Search">
                @using (@Html.BeginForm("search", "Shopping", FormMethod.Get))
                {
                    @Html.TextBox("Search", null, new { @class = "textSrch", @placeholder = "Search for items, brands" })
                    <img src="~/img/search-svgrepo-com.svg" class="srch" alt="search" />
                }
            </div>
            <div class="Admin-Cont">
                <div class="Admin"><a href="/Login/Index" id="a">I'm Admin</a></div>
            </div>
            <nav>
                <div class="Cart">
                    <div class="color" style="position: absolute; top: 60px; right: 18%;">
                        <img src="~/img/shopping-cart.svg" alt="cart" /><span id="cart">@Html.Partial("_ShoppingCart")</span>
                    </div>
                </div>
                <div class="User">
                    <img src="~/img/user.svg" alt="User" /><span>Sign in</span>
                </div>
            </nav>
        </header>

        <section>
            @RenderBody()
        </section>

        <footer>
            <a href="/Shopping"><img src="~/img/Logo.png" /></a>
            <p>
                Copyright © 2020, All Rights Reserved.
            </p>
            <span class="realized">
                realized by :
                <a class="name"> Hamza Boulila</a>
            </span>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

</body>
</html>

The Brand/Views/Shared/_ShoppingCart.cshtml
        @if (Session["CartCounter"] == null)
        {
            @Html.ActionLink("Cart:0", "ShoppingCart", "Shopping", new { id = "cartItem" })

        }
        else
        {
            @Html.ActionLink("Cart:" + Session["CartCounter"] , "ShoppingCart", "Shopping", new { id = "cartItem" })

        }